// pos-backend/config/planTiers.js

const TIERS = {
    emprendedor: {
        label: "Emprendedor",
        limits: {
            maxUsers: 4,
            maxAdmins: 1,
            maxCashiers: 1,
            maxWaiters: 2, // Camarero + Cocina combinados
            maxDishes: 60,
            maxTables: 12,
            maxClients: 1,
            maxRegisters: 1,
        },
        features: {
            // Básico
            tables: true,
            orders: true,
            menu: true,
            cashRegister: true,
            basicReports: true,
            employees: true,
            printers: true,

            // Bloqueado
            advancedReports: false,
            productReports: false,
            financialAnalysis: false,
            inventory: false,
            suppliers: false,
            purchases: false,
            inventoryCategories: true,
            fiscal: false,
            recipes: false,
            costing: false,
            margin: false,
            waste: false,
            expenses: false,
            financeSummary: false,
            payroll: false,
            accountsReceivable: false,
            multiClient: false,
            multiRegister: false,
            offlineMode: false,
        },
    },

    estandar: {
        label: "Estándar",
        limits: {
            maxUsers: 8,
            maxAdmins: 2,
            maxCashiers: 2,
            maxWaiters: 4,
            maxDishes: 120,
            maxTables: 30,
            maxClients: 1,
            maxRegisters: 2,
        },
        features: {
            tables: true,
            orders: true,
            menu: true,
            cashRegister: true,
            basicReports: true,
            employees: true,
            printers: true,

            advancedReports: true,
            productReports: true,
            financialAnalysis: false,
            inventory: true,
            suppliers: true,
            purchases: true,
            inventoryCategories: true,

            fiscal: false,
            recipes: false,
            costing: false,
            margin: false,
            waste: false,

            expenses: false,
            financeSummary: false,
            payroll: false,
            accountsReceivable: false,
            multiClient: false,
            multiRegister: true,
            offlineMode: false,
        },
    },

    premium: {
        label: "Premium",
        limits: {
            maxUsers: 15,
            maxAdmins: 3,
            maxCashiers: 3,
            maxWaiters: 9,
            maxDishes: null,
            maxTables: null,
            maxClients: 1,
            maxRegisters: 4,
        },
        features: {
            tables: true,
            orders: true,
            menu: true,
            cashRegister: true,
            basicReports: true,
            employees: true,
            printers: true,

            advancedReports: true,
            productReports: true,
            financialAnalysis: true,
            inventory: true,
            suppliers: true,
            purchases: true,
            inventoryCategories: true,

            fiscal: true,
            recipes: true,
            costing: true,
            margin: true,
            waste: true,

            expenses: true,
            financeSummary: true,
            payroll: false,
            accountsReceivable: false,
            multiClient: false,
            multiRegister: true,
            offlineMode: true,
        },
    },

    pro: {
        label: "Pro",
        limits: {
            maxUsers: null,
            maxAdmins: null,
            maxCashiers: null,
            maxWaiters: null,
            maxDishes: null,
            maxTables: null,
            maxClients: null,
            maxRegisters: null,
        },
        features: {
            tables: true,
            orders: true,
            menu: true,
            cashRegister: true,
            basicReports: true,
            employees: true,
            printers: true,

            advancedReports: true,
            productReports: true,
            financialAnalysis: true,
            inventory: true,
            suppliers: true,
            purchases: true,
            inventoryCategories: true,

            fiscal: true,
            recipes: true,
            costing: true,
            margin: true,
            waste: true,

            expenses: true,
            financeSummary: true,
            payroll: true,
            accountsReceivable: true,
            multiClient: true,
            multiRegister: true,
            offlineMode: true,
        },
    },
};

module.exports = TIERS;